baseURL = "https://itxiaozhang.com/"
title = "ITå°ç« "
languageCode = "zh-cn"
defaultContentLanguage = "zh"
theme = "PaperMod"

enableInlineShortcodes = true
enableEmoji = true
enableRobotsTXT = true

[outputs]
    home = ["HTML", "RSS", "JSON"]

[params]
    defaultTheme = "auto"
    ShowCodeCopyButtons = true
    ShowShareButtons = true
    ShowReadingTime = true
    ShowToc = false
    
    [params.profileMode]
        enabled = true
        title = "ITå°ç« "
        subtitle = "åˆ†äº«æŠ€æœ¯ï¼Œè®°å½•ç”Ÿæ´»"
        imageUrl = "/images/head.webp" # å ä½ç¬¦å¤´åƒ
        imageTitle = "ITå°ç« "
        imageWidth = 120
        imageHeight = 120

        [[params.profileMode.buttons]]
            name = "ç”µè„‘ç»´ä¿®"
            url = "https://zhang9.cn/"
        [[params.profileMode.buttons]]
            name = "ç¼–ç¨‹å¼€å‘"
            url = "https://zhang9.cn/"

    # [params.homeInfoParams]
    #     Title = "ITå°ç« "
    #     Content = "åˆ†äº«æŠ€æœ¯ï¼Œè®°å½•ç”Ÿæ´»"

    [[params.socialIcons]]
        name = "bilibili"
        url = "https://space.bilibili.com/3546607630944387"
    [[params.socialIcons]]
        name = "youtube"
        url = "https://www.youtube.com/@itxiaozhang"
    [[params.socialIcons]]
        name = "rss"
        url = "https://itxiaozhang.com/index.xml"

    [params.assets]
        disableHLJS = false
        favicon = "/images/favicon.ico"
        favicon16x16 = "/images/favicon.ico"
        favicon32x32 = "/images/favicon.ico"
        apple_touch_icon = "/images/apple-touch-icon.png"
        safari_pinned_tab = "/images/favicon.svg"

    [params.cover]
        hidden = true # ç¦ç”¨æ–‡ç« åˆ—è¡¨ç¼©ç•¥å›¾ 

[markup]
    [markup.highlight]
        noClasses = false
        anchorLineNos = true
        codeFences = true
        guessSyntax = true
        lineNos = true
        style = "monokai"
    [markup.goldmark.renderer]
        unsafe = true # å…è®¸åµŒå…¥ HTML

[menu]
    [[menu.main]]
        identifier = "home"
        name = "ğŸ  é¦–é¡µ"
        url = "/"
        weight = 10
    [[menu.main]]
        identifier = "posts"
        name = "ğŸ“š æ–‡ç« "
        url = "/posts/"
        weight = 15
    [[menu.main]]
        identifier = "archives"
        name = "â±ï¸ å½’æ¡£"
        url = "/archives/"
        weight = 20
    [[menu.main]]
        identifier = "search"
        name = "ğŸ” æœç´¢"
        url = "/search/"
        weight = 40
    [[menu.main]]
        identifier = "about"
        name = "ğŸ™‹ å…³äº"
        url = "/about/"
        weight = 50
